"""empty message

Revision ID: 463176e69453
Revises: 
Create Date: 2020-12-16 15:35:46.039053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463176e69453'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id_application', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('id_lecturer', sa.Integer(), nullable=False),
    sa.Column('id_course', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_application', 'id_student', 'id_lecturer', 'id_course')
    )
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('amount_of_students', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('lecturer',
    sa.Column('id_lecturer', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_lecturer')
    )
    op.create_table('student',
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('collective', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_student')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('lecturer')
    op.drop_table('course')
    op.drop_table('application')
    # ### end Alembic commands ###
